@startuml
skinparam rectangleRoundCorner 10
rectangle Experiment #lightgreen
rectangle Stimulus #lightgreen
rectangle Behavior #lightgreen
storage Logger
storage Interface
database database
Logger<-up->database
Experiment -down--> Stimulus
Experiment -down--> Behavior
Experiment <.down.> Logger
Stimulus <.up.> Logger
Behavior <.left.> Logger
Stimulus <.down.> Interface
Behavior <.down.> Interface
Logger <.right.> Interface
note right of Experiment : <size:10>Main state experiment</size>
note right of Behavior : <size:10>Handles the animal behavior</size> \n <size:10>in the experiment</size>
note left of Stimulus : <size:10>Handles the stimuli</size> \n <size:10>used in the experiment</size>
note left of Logger : <size:10>Handles all database</size> \n <size:10>interactions</size>
note left of Interface : <size:10>Handles all communication</size> \n <size:10>with hardware</size>
note left of database : <size:10>Data storage in:</size> \n<size:10>lab_experiments</size> \n<size:10>lab_behavior</size> \n<size:10>lab_stimuli</size>
@enduml